# This is a basic workflow to help you get started with Actions

name: autominify

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
        
      - name: Auto Minify
        uses: nizarmah/auto-minify@v1.9
        with:
          directory: 'src'
          
      - name: Auto committing minified files
        uses: stefanzweifel/git-auto-commit-action@v4.4.0
        with:
          commit_message: "Github Action: Auto Minified JS and CSS files"
          branch: ${{ github.ref }}  
