name: continuous integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  minify:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
        
      - name: Auto Minify
        uses: nizarmah/auto-minify@v1.9
        with:
          directory: 'src'
          
      - name: Auto committing minified files
        uses: stefanzweifel/git-auto-commit-action@v4.4.0
        with:
          commit_message: "Github Action: Auto Minified JS and CSS files"
          branch: ${{ github.ref }}  
  publish:
    runs-on: ubuntu-latest
    needs: [ minify ]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}      
      with: 
        branches: 'master'
